VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISolverFile"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' Solver uses a model file to solve

Public Sub ReadResults(s As COpenSolver, Optional solution As String)
End Sub

Public Property Get FileType() As OpenSolver_FileType
End Property

